name: Test using pytest

on: 
    push:
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]  # Test on multiple Python versions
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}

        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install pytest pytest-cov pytest-xdist
          pip install .[test]

      - name: Run tests
        env:
          HDF5_USE_FILE_LOCKING: "FALSE"
          PYTHONUNBUFFERED: "1"
          CI: "true"
        run: |
          python -m pytest tests/ -v -s --tb=short --junit-xml=junit.xml -n 0

      - name: Upload coverage report ${{ matrix.python-version }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: htmlcov

      - name: Upload test report ${{ matrix.python-version }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.python-version }}
          path: junit.xml